global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'process_exporter'
    static_configs:
      - targets: ['process_exporter:9256']

  - job_name: 'custom_exporter'
    static_configs:
      - targets: ['custom_exporter:9101']

  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Модуль проверки, настраиваемый в конфигурации blackbox
    static_configs:
      - targets: ['http://nginx']  # таргеты
    relabel_configs:
      - source_labels: [credit-score]
        target_label: __param_target
      - target_label: credit-score
        replacement: blackbox_exporter:9115  # Адрес blackbox-exporter

  - job_name: 'nginx'
    metrics_path: /nginx_status  # маршрут в nginx
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
