global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'credit-score-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
    basic_auth:
      username: 'your-username'
      password: 'your-password'
  