global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  # Scrape configuration for Process Exporter.
  - job_name: 'process_exporter'
    static_configs:
      - targets: ['process_exporter:9256']

  # Scrape configuration for Grafana.
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'ssl_check'
    metrics_path: /probe
    params:
      module: [http_2xx_ssl]  # Модуль, определенный в blackbox.yml
    static_configs:
      - targets:
          - https://localhost  # URL для проверки SSL
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox_exporter:9115  # Адрес Blackbox Exporter

#  - job_name: 'app'
#    static_configs:
#      - targets: ['app:8080']
#
#  - job_name: 'nginx'
#    metrics_path: /nginx_status  # маршрут в nginx
#    static_configs:
#      - targets: ['nginx:80']
#
#  - job_name: 'postgres_exporter'
#    static_configs:
#      - targets: ['postgres_exporter:9187']
