# prometheus.yml
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'process_exporter'
    static_configs:
      - targets: ['process_exporter:9256']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'ssl_check'
    metrics_path: /probe
    params:
      module: [http_2xx_ssl]  # Модуль, определенный в blackbox.yml
    static_configs:
      - targets:
          - https://localhost  # URL для проверки SSL
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox_exporter:9115  # Адрес Blackbox Exporter

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
