{
 "title": "Prometheus Nodes",
 "description": "Automatically create a row by node, with percentage of cpu, memory and filesystem used.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_boot_time_seconds, kubernetes_node)"
   }
  ]
 },
 "panels": [
  { "title": "[[node]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Cpu utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"idle\"}[5m]))) * 100",
     "legendFormat": "%age of use"
    }
   ]
  },
  {
   "title": "Cpu utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"idle\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{kubernetes_node=~\"$node\"} - node_memory_MemFree_bytes{kubernetes_node=~\"$node\"} - node_memory_Buffers_bytes{kubernetes_node=~\"$node\"} - node_memory_Cached_bytes{kubernetes_node=~\"$node\"}) / node_memory_MemTotal_bytes{kubernetes_node=~\"$node\"}) * 100",
     "legendFormat": "%age of use"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{kubernetes_node=~\"$node\"} - node_memory_MemFree_bytes{kubernetes_node=~\"$node\"} - node_memory_Buffers_bytes{kubernetes_node=~\"$node\"} - node_memory_Cached_bytes{kubernetes_node=~\"$node\"}) / node_memory_MemTotal_bytes{kubernetes_node=~\"$node\"}) * 100",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "File System use",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",kubernetes_node=~\"$node\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",kubernetes_node=~\"$node\"})",
     "legendFormat": "use"
    }
   ]
  },
  {
   "title": "File System use",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",kubernetes_node=~\"$node\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",kubernetes_node=~\"$node\"})",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  }
 ]
}