services:

  prometheus:
    image: prom/prometheus:v2.53.3
    container_name: prometheus
    networks:
      - credit-score-network
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../prometheus/prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml
      - ../exporter/:/etc/prometheus/exporters
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:12.0.0
    container_name: grafana
    networks:
      - credit-score-network
    ports:
      - "3000:3000"
    volumes:
      - ../grafana/dashboards:/var/lib/grafana/dashboards
      - ../grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    command: [ "--config", "/etc/grafana/grafana.ini" ]

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    networks:
      - credit-score-network
    ports:
      - "9100:9100"

networks:
  credit-score-network:
    driver: bridge
